In [13]:
import numpy as np
import json_tricks
answer = {}


inputs = json_tricks.load('inputs/inputs.json')

np.show_config()

Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.11.10/lib/python3.11/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.11.10/lib/python3.11/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Haswell MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.11.10/lib/python3.11/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.11.10/lib/python3.11/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Haswell MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
Compilers:
  c:
    commands: cc
    linker: ld.bfd
  

# Matrix Product II

$$A_{5 \times 10} \  B_{10 \times 2}\ C_{2 \times 30}\ D_{30 \times 3}\ E_{3 \times 9}$$

1. What will be the shape of the resulting matrix?
2. How many multiplication of numbers are required at best?

In [2]:
answer['task1'] = {
    '1': (5, 9),
    '2': 424
}



# Numpy expression

Using Numpy, write a function that calculates the 
following expression:

$$\exp(A^T(B + 2C) + 3I) \mathbf x,$$

where $I$ is an identity matrix of the necessary shape.

In [ ]:

def numpy_expression(A, B, C, x):
    N = A.shape[-1]
    M = B.shape[-1]

    res = np.exp(A.T @ (B + (2 * C)) + (3 * np.eye(N, M))) @ x
    print(res)
    return res.astype(float)

[[-2.68562044e-01]
 [ 7.88735520e+04]
 [ 4.81151377e+06]
 [ 1.35335733e-01]]
[[ 4.83099055e+07]
 [-6.01302394e+06]
 [-5.56431877e+36]]
[[-6.15130206e+16]
 [-5.34323729e+13]]
[[-8.03421478e+01]
 [-1.72449262e+16]
 [-4.81041714e+06]]
[[-3.95644720e+09]
 [-8.13776957e+05]]
[[1.69146291e+10]
 [7.78305278e-20]]
[[ 1.12183580e+09]
 [ 2.14427565e+14]
 [-6.60793974e+04]]
[[-3.50836795e+21]
 [ 5.21782482e+18]
 [ 1.48593859e-11]]
[[2.83075330e+23]
 [1.44625688e+12]]
[[5.57893619e-10]
 [5.14359733e+16]
 [1.77722210e+07]]


In [4]:
answer['task2'] = []
for one_input in inputs['task2']:
    answer['task2'].append(numpy_expression(**one_input))


[[-2.68562044e-01]
 [ 7.88735520e+04]
 [ 4.81151377e+06]
 [ 1.35335733e-01]]
[[ 4.83099055e+07]
 [-6.01302394e+06]
 [-5.56431877e+36]]
[[-6.15130206e+16]
 [-5.34323729e+13]]
[[-8.03421478e+01]
 [-1.72449262e+16]
 [-4.81041714e+06]]
[[-3.95644720e+09]
 [-8.13776957e+05]]
[[1.69146291e+10]
 [7.78305278e-20]]
[[ 1.12183580e+09]
 [ 2.14427565e+14]
 [-6.60793974e+04]]
[[-3.50836795e+21]
 [ 5.21782482e+18]
 [ 1.48593859e-11]]
[[2.83075330e+23]
 [1.44625688e+12]]
[[5.57893619e-10]
 [5.14359733e+16]
 [1.77722210e+07]]


# Einstein's Rule

In *Tensor Algebra*, a direct generalization of the Linear Algebra to the case of $N$-dimentional tables called *tensors* (normal matrix), the Einstein's rule exists.

It works as follows: if you see a duplicating upper and lower index in the formula, that means, this index convolves.

For example, the following tensor expression, summation and matrix product are equivalent:

$$a_k^l b_l^m = \sum_{l=1}^L a_k^l b_l^m = AB$$

In this notation subscript means row index and superscript means column index.

<details>
<summary> Note </summary>

> [!NOTE]
> Also at some point it will be important to know that:
> * lower index represents a contravariant dimension of a
> tensor
> * upper index represents a covariant dimension 
> of tensor. But let us omit this part for now.

</details>

# Task

Calculate the following expression written using Einstein's 
rule:

$$a_k^m b_m^n c_n^o d_l^k$$

In [5]:
def einsteins_rule(A, B, C, D):
    res = (D @ (A @ B @ C)) 
    return res

In [6]:
answer['task3'] = []
for one_input in inputs['task3']:
    answer['task3'].append(einsteins_rule(**one_input))

# answer['task3']

# Diagonal Matrix Product

You are given two square matrices: $A$ and $D$, where $A$ is a 
full matrix and $D$ is a diagonal matrix:

$$
A = \begin{bmatrix}
- & \mathbf a_1 & - \\
& \vdots & \\
- & \mathbf a_N & - \\
\end{bmatrix}
$$

$$
D = \textrm{diag}(d_1, d_2, \dots, d_N) = \begin{bmatrix}
d_1 & & & & \\
& d_2 & & & \\
& & d_3 & & \\
& & & \ddots & \\
& & & & d_N 
\end{bmatrix}
$$

Write a program to calculate the result of $DA$ and $AD$ in 
the fastest possible way.

In [7]:
def diag_prod_DA(A, D):
    res = A.copy()
    D_diag = np.diag(D)

    for i in range(A.shape[0]):
        res[i, :] = D_diag[i] * res[i, :]

    return res

def diag_prod_AD(A, D):
    res = A.copy()

    D_diag = np.diag(D)
    for i in range(A.shape[1]):
        res[:, i] = D_diag[i] * res[:, i]
    
    return res

In [8]:
answer['task4_1'] = []
answer['task4_2'] = []
for one_input in inputs['task4']:
    answer['task4_1'].append(diag_prod_DA(**one_input))
    answer['task4_2'].append(diag_prod_AD(**one_input))

# Sparse Matrix Product

You are given two matrices of the same shape: $A$ and $B$. Matrix $A$ is full
and is given in the form of `numpy.ndarray`.

The second matrix $B$ is **sparse**. That means that the 
majority of the items are equal to $0$ except for $M$. This matrix is given
as a set of non-zero elements of this matrix in form of $3 \times M$ `numpy.ndarray` as row-column-value tuple (COO sparse matrix form):

$$
\begin{bmatrix}
r_1 & c_1 & v_1 \\
r_2 & c_2 & v_2 \\
& \vdots & \\
r_M & c_M & v_M \\
\end{bmatrix}
$$

If in this struct two items correspond to the same location, consider the latter is correct.

Write the most efficient program that calculates $AB$.

Also return the ratio between the number of multiplication operations that are needed to calculate the sparse product and the number of operations for full product.

In [9]:
def sparse_matrix_product(A, B_sparse):
    ops = 0

    N, M = A.shape[0], int(B_sparse[1].max()) + 1
    res = np.zeros((N, M))

    not_duplicated = {}
    for r, c, v in B_sparse.T:
        not_duplicated[int(r), int(c)] = v

    for (r, c), v in not_duplicated.items():
        r, c = int(r), int(c)
        ops += 1
        res[:, c] += A[:, r] * v 

    ratio = (ops * N) / (A.shape[0] * A.shape[1] * M)
    print(res)
    return res, ratio


In [10]:
answer['task5'] = []
for one_input in inputs['task5']:
    answer['task5'].append(sparse_matrix_product(**one_input))

[[  0. -16.]
 [ 15. -16.]
 [-27.  20.]
 [ -3.  -4.]]
[[  0.  12.  12.]
 [ 37. -12.  25.]
 [-13.   3.   8.]]
[[  0.  16. -16.]
 [  0.  16. -16.]]
[[ -7.   2.  -3.]
 [-15. -18.   1.]
 [ -9.  -6.  -1.]]
[[-2.  0.  0.  3.]
 [-8.  0.  0. 12.]]
[[ -5.  -4.]
 [  9. -12.]]
[[ 10.   8.   0.   0.]
 [-15.  12.   0.  -5.]
 [ 10.  15.   0.  -3.]]
[[ 8.  0.  2.  4.]
 [-4.  0.  0. -2.]
 [-2.  0. 10. -1.]]
[[  9.   8.   0.   0.]
 [-24.  -6. -10.   0.]]
[[-3.]
 [ 4.]
 [ 1.]]


In [11]:
json_tricks.dump(answer, '.answer.json')

'{"task1": {"1": [5, 9], "2": 424}, "task2": [{"__ndarray__": [[-0.26856204365326736], [78873.55195599546], [4811513.768811148], [0.1353357330694552]], "dtype": "float64", "shape": [4, 1], "Corder": true}, {"__ndarray__": [[48309905.5069236], [-6013023.936897506], [-5.564318773958797e+36]], "dtype": "float64", "shape": [3, 1], "Corder": true}, {"__ndarray__": [[-6.151302057665034e+16], [-53432372907627.31]], "dtype": "float64", "shape": [2, 1], "Corder": true}, {"__ndarray__": [[-80.34214775367059], [-1.72449261891118e+16], [-4810417.136659107]], "dtype": "float64", "shape": [3, 1], "Corder": true}, {"__ndarray__": [[-3956447203.449644], [-813776.9570950195]], "dtype": "float64", "shape": [2, 1], "Corder": true}, {"__ndarray__": [[16914629138.512087], [7.783052777144698e-20]], "dtype": "float64", "shape": [2, 1], "Corder": true}, {"__ndarray__": [[1121835797.5149987], [214427565087903.9], [-66079.39738442056]], "dtype": "float64", "shape": [3, 1], "Corder": true}, {"__ndarray__": [[-3.