# Determinant Computation Algorithm

Write a function that accepts a matrix in form of numpy array and calculates its determinant in the most efficient way (the algorithm will be tested on large matrices).

Use vectorized `numpy` operations.

You are allowed to use `numpy.linalg`

In [276]:
import numpy as np
import json_tricks
import scipy

In [ ]:
import scipy.linalg

# def determinant_fast(A):
#     A = np.array(A, dtype=float)
#     n = A.shape[0]
    
#     U = A.copy()
#     pivots = []

#     for i in range(n):
#         pivots_row = i + np.argmax(np.abs(U[i:, i])) 
        
#         if pivots_row != i:
#             U[[i, pivots_row]] = U[[pivots_row, i]]
#             pivots.append(-U[i, i])

#         else:
#             pivots.append(U[i, i])
        
#         for j in range(i + 1, n):  
#             if U[i, i] != 0:
#                 factor = U[j, i] / U[i, i]
#                 U[j, i:] -= factor * U[i, i:]

#     pivots = np.array(pivots)
#     det = np.prod(pivots)

#     return det, pivots

def determinant_fast(A):
    P, L, U = scipy.linalg.lu(A)
    
    det_u = np.prod(np.diag(U))
    det_l = np.prod(np.diag(L))
    det_p = np.linalg.det(P)
    det = det_l * det_u


    return det, np.diag(U), (P, L, U)

In [ ]:
inputs = json_tricks.load('inputs/inputs.json')
sol = json_tricks.load('.solution.json')

results = {'results': []}
for args in inputs['inputs']:
    res = determinant_fast(**args)
    results['results'].append(res)

json_tricks.dump(results, '.answer.json')


test = 7
res = determinant_fast(**inputs['inputs'][test])
print(f"det{test}:",{np.linalg.det(inputs['inputs'][test]['A'])})
print(res[0])
print(res[1].reshape(-1, 1).shape[0])
print(res[1].reshape(-1, 1))

## debug ##


print("SOLUTION:")
print("det:", sol['results'][test][0])
print("pivots:", sol['results'][test][1].reshape(-1, 1).shape[0])
print(sol['results'][test][1].reshape(-1, 1))

A: [[-1 -1]
 [ 0  0]]

P: [[1. 0.]
 [0. 1.]]

U: [[-1. -1.]
 [ 0.  0.]]

A: [[ 0  0  0  0 -1  0  0 -1 -1  0  0]
 [ 0  0 -1 -1  0  0  0  0 -1 -1 -1]
 [-1  0  0  0  0  0 -1  0  0 -1 -1]
 [-1 -1 -1 -1  0  0  0 -1 -1  0  0]
 [ 0 -1 -1  0 -1  0 -1  0  0  0 -1]
 [ 0  0  0  0  0  0 -1 -1 -1 -1  0]
 [-1 -1 -1 -1  0  0  0  0  0 -1 -1]
 [-1 -1 -1 -1  0 -1 -1  0  0  0  0]
 [ 0  0 -1 -1  0 -1 -1  0  0 -1  0]
 [ 0  0  0  0 -1 -1  0  0  0  0 -1]
 [-1 -1  0 -1 -1  0  0  0  0 -1  0]]

P: [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]]

U: [[-1.          0.          0.          0.          0.          0.
  -1.          0.          0.         -1.         -1.   