# Determinant Computation Algorithm

Write a function that accepts a matrix in form of numpy array and calculates its determinant in the most efficient way (the algorithm will be tested on large matrices).

Use vectorized `numpy` operations.

You are allowed to use `numpy.linalg`

In [16]:
import numpy as np
import json_tricks
from scipy.linalg import lu_factor, lu_solve
import numpy.linalg as la

In [17]:
def determinant_fast(A):
    P, L, U = scipy.linalg.lu(A)
    
    U_diag = np.diag(U)
    det_u = np.prod(U_diag)
    
    n = A.shape[0]
    p = []
    for i in range(n):
        p.append(np.argmax(P[i, :]))
    inversions = sum(1 for i in range(len(p)) for j in range(i + 1, len(p)) if p[i] > p[j])

    det = det_u * (-1) ** inversions
    # det = det_u 


    return det, U_diag, (P, L, U)

In [18]:
inputs = json_tricks.load('inputs/inputs.json')
sol = json_tricks.load('.solution.json')

results = {'results': []}
for args in inputs['inputs']:
    res = determinant_fast(**args)
    results['results'].append(res)

json_tricks.dump(results, '.answer.json')


test = 2
res = determinant_fast(**inputs['inputs'][test])
print(f"det from np.linalg.det test:{test}:",{np.linalg.det(inputs['inputs'][test]['A'])})

print("Matrix A")
print(inputs['inputs'][test]['A'])

print("===Answer===")
print(res[0])
print(res[1].reshape(-1, 1))

## debug ##
print("===Expected SOLUTION===")
print("det:", sol['results'][test][0])
print(sol['results'][test][1].reshape(-1, 1))

det from np.linalg.det test:2: {np.float64(-372.99999999999983)}
Matrix A
[[ 0  0  0 -1  0  0  0 -1  0 -1 -1 -1 -1  0  0  0 -1]
 [ 0 -1 -1 -1 -1  0  0  0  0 -1 -1 -1 -1 -1  0 -1  0]
 [-1 -1  0  0 -1  0  0  0 -1 -1  0 -1 -1  0  0 -1  0]
 [-1 -1 -1  0 -1 -1  0  0  0  0 -1  0 -1 -1 -1 -1  0]
 [-1  0  0  0 -1 -1  0  0  0 -1 -1 -1  0  0 -1 -1 -1]
 [-1 -1  0  0 -1 -1 -1  0 -1 -1  0 -1  0 -1 -1 -1 -1]
 [ 0 -1  0  0 -1 -1 -1 -1  0  0  0 -1 -1 -1  0 -1 -1]
 [ 0 -1  0 -1 -1 -1  0 -1  0 -1  0 -1  0  0  0  0  0]
 [-1  0 -1  0 -1 -1  0 -1 -1 -1  0 -1 -1  0 -1 -1  0]
 [-1  0  0 -1  0  0  0  0  0  0 -1  0 -1 -1 -1 -1  0]
 [ 0 -1 -1  0  0  0  0  0  0 -1 -1  0 -1  0 -1  0 -1]
 [ 0 -1  0 -1 -1  0 -1  0 -1 -1 -1 -1  0  0 -1 -1  0]
 [ 0 -1  0 -1 -1 -1  0 -1 -1 -1 -1  0 -1 -1  0 -1 -1]
 [ 0  0 -1 -1 -1  0  0 -1 -1  0  0  0  0  0 -1  0  0]
 [-1 -1  0  0 -1  0  0  0 -1  0  0  0 -1  0  0  0 -1]
 [-1 -1 -1 -1  0  0  0  0  0  0 -1  0  0 -1  0 -1 -1]
 [ 0  0 -1 -1 -1 -1 -1  0  0  0 -1 -1 -1 -1 -1 -1 -1]]
===Answ